version: "3.7"
services:
  app:
    container_name: docker-messaging-project
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "100:100"
    links:
      - db
    depends_on:
      - db
  db:
    container_name: message_db
    image: andresvidal/rpi3-mongodb3
    volumes:
      - ./db_data:/var/micro-data/mongodb/data/db
    restart: always
    ports:
      - "200:27017"
volumes:
  db_data:
